const dsPET = [
  {
    ID: "PET-001",
    Name: "Max",
    Image: "max.jpg",
    Age: 2,
    Price: 500000,
    Species: "Labrador",
    Gender: "Male",
    Describe:
      "Max là một chú Labrador thông minh, trung thành và rất thích chơi ngoài trời.",
  },
  {
    ID: "PET-002",
    Name: "Bella",
    Image: "bella.jpg",
    Age: 1,
    Price: 600000,
    Species: "Poodle",
    Gender: "Female",
    Describe:
      "Bella là một cô Poodle tinh nghịch, dễ thương và rất thích nhảy múa.",
  },
  {
    ID: "PET-003",
    Name: "Charlie",
    Image: "charlie.jpg",
    Age: 3,
    Price: 450000,
    Species: "Beagle",
    Gender: "Male",
    Describe:
      "Charlie là một chú Beagle ham khám phá, luôn tràn đầy năng lượng.",
  },
  {
    ID: "PET-004",
    Name: "Lucy",
    Image: "lucy.jpg",
    Age: 2,
    Price: 550000,
    Species: "Bulldog",
    Gender: "Female",
    Describe:
      "Lucy là một cô Bulldog hiền lành, thích được cưng nựng và ôm ấp.",
  },
  {
    ID: "PET-005",
    Name: "Rocky",
    Image: "rocky.jpg",
    Age: 4,
    Price: 700000,
    Species: "Husky",
    Gender: "Male",
    Describe:
      "Rocky là một Husky mạnh mẽ, năng động và thích vận động cường độ cao.",
  },
  {
    ID: "PET-006",
    Name: "Daisy",
    Image: "daisy.jpg",
    Age: 1,
    Price: 520000,
    Species: "Golden Retriever",
    Gender: "Female",
    Describe: "Daisy thân thiện, đáng yêu và rất thích chơi đùa với trẻ nhỏ.",
  },
  {
    ID: "PET-007",
    Name: "Milo",
    Image: "milo.jpg",
    Age: 3,
    Price: 480000,
    Species: "Shih Tzu",
    Gender: "Male",
    Describe: "Milo nhỏ nhắn, lông mềm mại, thích được âu yếm và vuốt ve.",
  },
  {
    ID: "PET-008",
    Name: "Luna",
    Image: "luna.jpg",
    Age: 2,
    Price: 510000,
    Species: "Boxer",
    Gender: "Female",
    Describe:
      "Luna tràn đầy năng lượng, thích vận động và rất trung thành với chủ.",
  },
  {
    ID: "PET-009",
    Name: "Toby",
    Image: "toby.jpg",
    Age: 5,
    Price: 750000,
    Species: "Rottweiler",
    Gender: "Male",
    Describe: "Toby mạnh mẽ, thông minh, luôn bảo vệ gia đình của mình.",
  },
  {
    ID: "PET-010",
    Name: "Coco",
    Image: "coco.jpg",
    Age: 2,
    Price: 495000,
    Species: "Chihuahua",
    Gender: "Female",
    Describe: "Coco nhỏ nhắn, đáng yêu và rất quấn chủ.",
  },
  {
    ID: "PET-011",
    Name: "Buddy",
    Image: "buddy.jpg",
    Age: 3,
    Price: 530000,
    Species: "Dalmatian",
    Gender: "Male",
    Describe: "Buddy nhanh nhẹn, thích chạy nhảy và có bộ lông đặc trưng.",
  },
  {
    ID: "PET-012",
    Name: "Molly",
    Image: "molly.jpg",
    Age: 2,
    Price: 460000,
    Species: "Pug",
    Gender: "Female",
    Describe: "Molly dễ thương, tròn trịa và thích được cưng chiều.",
  },
  {
    ID: "PET-013",
    Name: "Oscar",
    Image: "oscar.jpg",
    Age: 4,
    Price: 650000,
    Species: "German Shepherd",
    Gender: "Male",
    Describe: "Oscar dũng cảm, trung thành và rất thông minh.",
  },
  {
    ID: "PET-014",
    Name: "Ruby",
    Image: "ruby.jpg",
    Age: 1,
    Price: 480000,
    Species: "Corgi",
    Gender: "Female",
    Describe: "Ruby đáng yêu, lém lỉnh, rất thích chạy nhảy.",
  },
  {
    ID: "PET-015",
    Name: "Jack",
    Image: "jack.jpg",
    Age: 5,
    Price: 700000,
    Species: "Doberman",
    Gender: "Male",
    Describe: "Jack mạnh mẽ, can đảm, thích bảo vệ chủ nhân.",
  },
  {
    ID: "PET-016",
    Name: "Rosie",
    Image: "rosie.jpg",
    Age: 3,
    Price: 550000,
    Species: "French Bulldog",
    Gender: "Female",
    Describe: "Rosie thân thiện, dễ thương và thích chơi đùa.",
  },
  {
    ID: "PET-017",
    Name: "Teddy",
    Image: "teddy.jpg",
    Age: 2,
    Price: 490000,
    Species: "Maltese",
    Gender: "Male",
    Describe: "Teddy nhỏ nhắn, lông mềm mại và rất đáng yêu.",
  },
  {
    ID: "PET-018",
    Name: "Lily",
    Image: "lily.jpg",
    Age: 4,
    Price: 640000,
    Species: "Great Dane",
    Gender: "Female",
    Describe: "Lily to lớn nhưng hiền lành, thân thiện với mọi người.",
  },
  {
    ID: "PET-019",
    Name: "Sam",
    Image: "sam.jpg",
    Age: 1,
    Price: 455000,
    Species: "Cavalier King Charles",
    Gender: "Male",
    Describe: "Sam tình cảm, thích gần gũi với con người.",
  },
  {
    ID: "PET-020",
    Name: "Duke",
    Image: "duke.jpg",
    Age: 3,
    Price: 580000,
    Species: "Saint Bernard",
    Gender: "Male",
    Describe:
      "Duke khổng lồ nhưng hiền lành, thích chăm sóc và bảo vệ gia đình.",
  },
  {
    ID: "PET-021",
    Name: "Zoe",
    Image: "zoe.jpg",
    Age: 2,
    Price: 500000,
    Species: "Samoyed",
    Gender: "Female",
    Describe: "Zoe có bộ lông trắng muốt, vui vẻ và thân thiện với trẻ nhỏ.",
  },
  {
    ID: "PET-022",
    Name: "Rex",
    Image: "rex.jpg",
    Age: 4,
    Price: 620000,
    Species: "Akita Inu",
    Gender: "Male",
    Describe: "Rex trung thành, mạnh mẽ và thích chạy nhảy ngoài trời.",
  },
  {
    ID: "PET-023",
    Name: "Misty",
    Image: "misty.jpg",
    Age: 1,
    Price: 530000,
    Species: "Bichon Frise",
    Gender: "Female",
    Describe: "Misty nhỏ nhắn, đáng yêu và có bộ lông xoăn mềm mại.",
  },
  {
    ID: "PET-024",
    Name: "Leo",
    Image: "leo.jpg",
    Age: 3,
    Price: 550000,
    Species: "Border Collie",
    Gender: "Male",
    Describe: "Leo thông minh, nhanh nhẹn và rất dễ huấn luyện.",
  },
  {
    ID: "PET-025",
    Name: "Penny",
    Image: "penny.jpg",
    Age: 2,
    Price: 490000,
    Species: "Papillon",
    Gender: "Female",
    Describe: "Penny nhỏ nhắn, lanh lợi và rất tình cảm.",
  },
  {
    ID: "PET-026",
    Name: "Thor",
    Image: "thor.jpg",
    Age: 5,
    Price: 700000,
    Species: "Alaskan Malamute",
    Gender: "Male",
    Describe: "Thor mạnh mẽ, kiên trì và thích vận động.",
  },
  {
    ID: "PET-027",
    Name: "Nala",
    Image: "nala.jpg",
    Age: 2,
    Price: 460000,
    Species: "Shiba Inu",
    Gender: "Female",
    Describe: "Nala nhanh nhẹn, tinh nghịch và rất trung thành.",
  },
  {
    ID: "PET-028",
    Name: "Buster",
    Image: "buster.jpg",
    Age: 3,
    Price: 600000,
    Species: "Bull Terrier",
    Gender: "Male",
    Describe: "Buster năng động, dũng cảm và thích chơi đùa.",
  },
  {
    ID: "PET-029",
    Name: "Dolly",
    Image: "dolly.jpg",
    Age: 1,
    Price: 480000,
    Species: "Yorkshire Terrier",
    Gender: "Female",
    Describe: "Dolly nhỏ nhắn, đáng yêu và rất quấn chủ.",
  },
  {
    ID: "PET-030",
    Name: "Rusty",
    Image: "rusty.jpg",
    Age: 4,
    Price: 640000,
    Species: "Australian Shepherd",
    Gender: "Male",
    Describe: "Rusty thông minh, nhanh nhẹn và rất năng động.",
  },
  {
    ID: "PET-031",
    Name: "Maggie",
    Image: "maggie.jpg",
    Age: 2,
    Price: 500000,
    Species: "Cocker Spaniel",
    Gender: "Female",
    Describe: "Maggie hiền lành, thân thiện và thích được vuốt ve.",
  },
  {
    ID: "PET-032",
    Name: "Zeus",
    Image: "zeus.jpg",
    Age: 5,
    Price: 690000,
    Species: "Bernese Mountain Dog",
    Gender: "Male",
    Describe: "Zeus to lớn nhưng dịu dàng, thân thiện với mọi người.",
  },
  {
    ID: "PET-033",
    Name: "Lacey",
    Image: "lacey.jpg",
    Age: 1,
    Price: 520000,
    Species: "Havanese",
    Gender: "Female",
    Describe: "Lacey nhỏ nhắn, đáng yêu và rất tình cảm.",
  },
  {
    ID: "PET-034",
    Name: "Bruno",
    Image: "bruno.jpg",
    Age: 3,
    Price: 570000,
    Species: "Basset Hound",
    Gender: "Male",
    Describe: "Bruno hiền lành, kiên nhẫn và có đôi tai đặc trưng.",
  },
  {
    ID: "PET-035",
    Name: "Fiona",
    Image: "fiona.jpg",
    Age: 2,
    Price: 490000,
    Species: "Scottish Terrier",
    Gender: "Female",
    Describe: "Fiona độc lập, thông minh và có phong thái quý tộc.",
  },
  {
    ID: "PET-036",
    Name: "Shadow",
    Image: "shadow.jpg",
    Age: 4,
    Price: 610000,
    Species: "Siberian Husky",
    Gender: "Male",
    Describe: "Shadow mạnh mẽ, thích chạy nhảy và rất trung thành.",
  },
  {
    ID: "PET-037",
    Name: "Ginger",
    Image: "ginger.jpg",
    Age: 3,
    Price: 530000,
    Species: "Miniature Schnauzer",
    Gender: "Female",
    Describe: "Ginger thông minh, năng động và dễ huấn luyện.",
  },
  {
    ID: "PET-038",
    Name: "Bailey",
    Image: "bailey.jpg",
    Age: 2,
    Price: 550000,
    Species: "Whippet",
    Gender: "Male",
    Describe: "Bailey nhanh nhẹn, thanh lịch và rất trung thành.",
  },
  {
    ID: "PET-039",
    Name: "Duke",
    Image: "duke2.jpg",
    Age: 3,
    Price: 590000,
    Species: "Jack Russell Terrier",
    Gender: "Male",
    Describe: "Duke tinh nghịch, thông minh và rất hoạt bát.",
  },
  {
    ID: "PET-040",
    Name: "Dixie",
    Image: "dixie.jpg",
    Age: 2,
    Price: 490000,
    Species: "Airedale Terrier",
    Gender: "Female",
    Describe: "Dixie tò mò, thông minh và rất dễ huấn luyện.",
  },
];
module.exports = dsPET;
